services:
  postgres:
    image: postgres
    container_name: postgres-bot
    restart: always
    env_file:
      - .env
    ports:
      - 5434:5432

  adminer:
    image: adminer
    container_name: adminer-bot
    restart: always
    ports:
      - 8082:8080

volumes:
  bot_db:
    external: true

networks:
  default:
